# Generated by Django 4.2.4 on 2023-09-17 10:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ava',
            field=models.ImageField(default='', upload_to=accounts.models.ava_upload_to),
            preserve_default=False,
        ),
    ]
