# Generated by Django 4.2.5 on 2023-09-28 15:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ava',
            field=models.ImageField(default='users/avas/default.png', upload_to=accounts.models.ava_upload_to),
        ),
    ]
