# Generated by Django 5.0.1 on 2024-01-17 16:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_ava'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[accounts.models.validate_timezone]),
        ),
    ]
