# Generated by Django 4.2.5 on 2023-09-28 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked_%(app_label)s_%(class)ss', related_query_name='disliked_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_%(app_label)s_%(class)ss', related_query_name='liked_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='viewed_by',
            field=models.ManyToManyField(related_name='viewed_posts', related_query_name='related_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked_%(app_label)s_%(class)ss', related_query_name='disliked_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_%(app_label)s_%(class)ss', related_query_name='liked_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked_%(app_label)s_%(class)ss', related_query_name='disliked_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_%(app_label)s_%(class)ss', related_query_name='liked_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
