# Generated by Django 4.2.5 on 2023-10-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_post_text_comment_disliked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='', max_length=25000),
            preserve_default=False,
        ),
    ]
