# Generated by Django 4.2.7 on 2023-11-30 15:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='upd_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(
                2022,
                5,
                11,
                5,
                5,
                5,
                tzinfo=datetime.timezone.utc
            )),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='upd_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='upd_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
