# Generated by Django 5.0.2 on 2024-06-01 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_comment_pub_date_comment_upd_date_post_pub_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('new post', 'New Post'), ('new subscriber', 'New Subscriber'), ('post commented', 'Post Commented'), ('comment replied', 'Comment Replied'), ('reply replied', 'Reply Replied')])),
                ('object_pk', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
