# Generated by Django 5.0.2 on 2024-06-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_post', 'New Post'), ('new_subscriber', 'New Subscriber'), ('post_commented', 'Post Commented'), ('comment_replied', 'Comment Replied'), ('reply_replied', 'Reply Replied')]),
        ),
    ]
