# Generated by Django 5.0.2 on 2024-06-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('newPost', 'New Post'), ('newSubscriber', 'New Subscriber'), ('postCommented', 'Post Commented'), ('commentReplied', 'Comment Replied'), ('replyReplied', 'Reply Replied')]),
        ),
    ]
